#!/bin/bash

set -e

ROSDISTRO_PACKAGE=${ROSDISTRO_PACKAGE:-desktop_full}
mkdir -p build
rosinstall_generator $ROSDISTRO_PACKAGE --rosdistro indigo --deps --tar --flat > build/ws.rosinstall
wstool init -j8 build/src build/ws.rosinstall
PACKAGES=$(ls build/src)
cp -RL debian build/src/debian
echo $PACKAGES > build/src/debian/packages.txt
echo "3.0 (native)" > build/src/debian/source/format

DEPS=$(python -m rosdep_lite.deps_from_workspace build/src trusty)
cat << EOF > build/src/debian/control
Source: roscon-demo-sdk
Maintainer: Mike Purvis <mpurvis@clearpath.ai>
Section: devel
Priority: extra
Standards-Version: 3.9.5
Build-Depends: ${DEPS}
Homepage: http://clearpathrobotics.com

Package: roscon-demo-sdk
Architecture: amd64
Depends: ${DEPS}
Description: Demonstration ROS SDK bundle.
EOF

cd build/src
dpkg-buildpackage -uc -us -S -d
