#!/bin/bash

set -e

mkdir -p build
rosinstall_generator ros_base --rosdistro indigo --deps --tar --flat > build/ros_base.rosinstall
wstool init -j8 build/src build/ros_base.rosinstall
PACKAGES=$(ls build/src)
cp -RL debian build/src/debian
echo $PACKAGES > build/src/debian/packages.txt
echo "3.0 (native)" > build/src/debian/source/format

DEPS=$(python -m rosdep_lite.deps_from_workspace build/src trusty)
cat << EOF > build/src/debian/control
Source: roscon-base
Maintainer: Mike Purvis <mpurvis@clearpath.ai>
Section: devel
Priority: extra
Standards-Version: 3.9.5
Build-Depends: ${DEPS}
Homepage: http://clearpathrobotics.com

Package: roscon-base
Architecture: amd64
Depends: ${DEPS}
Description: Bundle of ROS base.
EOF

cd build/src
dpkg-buildpackage -uc -us -S -d
