#!/bin/bash

set -e

mkdir -p build
rosinstall_generator ros_base --rosdistro indigo --deps --tar --flat > ros_base.rosinstall
wstool init -j8 build/src ros_base.rosinstall
DEPS=$(./compute_deps)
cp -RL debian build/src/debian

cat << EOF > build/src/debian/control
Source: roscon-base
Maintainer: Mike Purvis <mpurvis@clearpath.ai>
Section: devel
Priority: extra
Standards-Version: 3.9.5
Build-Depends: ${DEPS}
Homepage: http://clearpathrobotics.com

Package: roscon-base
Architecture: amd64
Depends: ${DEPS}
Description: Bundle of ROS base.
EOF

cd build/src
dpkg-buildpackage -uc -us -S -d
